[[rules]]
  description = "check credential leak"
  # regex = '''secret(.{0,20})['|"]([0-9a-zA-Z-._{}$\/\+=]{20,120})['|"]'''
  regex = '''dler.cloud/[0-9a-zA-Z-._{}$\/\+=]{15,20}'''
  [[rules.Entropies]]
	Min = "4"
        Max = "8.0"
